void kputchar(int c);
int output_init();
void kputs(char *p);
void kputsn(char *p, int n);
void kputuint(int x);
void kputuhex(int x);
void kputint(int x);
void kputhex(int x);
void kprint_write_info();
void kprintf(char *format, ...);
void set_fcolor(int color);
void set_bcolor(int color);